/// <summary>
/// Generates the opt-in alias props file the package ships.
/// </summary>
/// <remarks>
/// OpenXmlKit gives its types the names they should have — Paragraph, Table, Font, Style — which
/// are the names the SDK's Wordprocessing namespace already uses. A project importing both gets
/// CS0104 on every one of them.
/// <para>
/// The way out is per-type aliases rather than renamed types, opted into by setting
/// OpenXmlKitAliases in the consuming project. In alias mode the consumer never imports
/// OpenXmlKit.Word at all, so the bare names never enter scope and there is nothing to be ambiguous
/// about; what it gets instead is WParagraph, or WordParagraph, alongside the SDK's own names.
/// </para>
/// <para>
/// Generated rather than hand-written, because a list of every public type maintained by hand goes
/// stale the first time one is added, and the failure is a consumer's build breaking rather than
/// ours.
/// </para>
/// </remarks>
public static class AliasProps
{
    public static string Generate()
    {
        var builder = new StringBuilder();
        builder.AppendLine("<Project>");
        builder.AppendLine();
        builder.AppendLine("  <!--");
        builder.AppendLine("    Generated by OpenXmlKit.Tests.AliasPropsTests. Do not edit by hand.");
        builder.AppendLine();
        builder.AppendLine("    OpenXmlKit names its types after what they are, which is what the SDK's Wordprocessing");
        builder.AppendLine("    namespace does too. A project that imports both gets an ambiguous reference on every");
        builder.AppendLine("    shared name. Setting OpenXmlKitAliases gives prefixed aliases instead:");
        builder.AppendLine();
        builder.AppendLine("      <PropertyGroup>");
        builder.AppendLine("        <OpenXmlKitAliases>W</OpenXmlKitAliases>");
        builder.AppendLine("      </PropertyGroup>");
        builder.AppendLine();
        builder.AppendLine("    The value is either W or Word, giving WParagraph or WordParagraph.");
        builder.AppendLine();
        builder.AppendLine("    In alias mode, do not also import OpenXmlKit.Word. An alias avoids the ambiguity by");
        builder.AppendLine("    keeping the bare names out of scope; importing the namespace as well puts them back.");
        builder.AppendLine("  -->");

        foreach (var prefix in new[] { "W", "Word" })
        {
            builder.AppendLine();
            builder.AppendLine($"  <ItemGroup Condition=\"'$(OpenXmlKitAliases)' == '{prefix}'\">");
            foreach (var type in PublicTypes())
            {
                builder.AppendLine($"    <Using Include=\"{type.FullName}\" Alias=\"{prefix}{type.Name}\" />");
            }

            builder.AppendLine("  </ItemGroup>");
        }

        builder.AppendLine();
        builder.AppendLine("</Project>");
        return builder.ToString();
    }

    /// <summary>
    /// Every exported type, in a stable order so the generated file does not churn.
    /// </summary>
    public static IEnumerable<Type> PublicTypes() =>
        typeof(Document).Assembly
            .GetExportedTypes()
            .Where(_ => !_.IsNested)
            .OrderBy(_ => _.Namespace, StringComparer.Ordinal)
            .ThenBy(_ => _.Name, StringComparer.Ordinal);
}
