using System.Text.Json;

/// <summary>
/// Generates the schema order table <see cref="SchemaOrder"/> ships.
/// </summary>
/// <remarks>
/// The order a container's children have to appear in is not something to transcribe from the
/// specification by hand — that is what the estate was already doing in three places, and what the
/// table replaced. It is read from the SDK's own schema data, the same files its code generator
/// reads particle order from, vendored beside this under SchemaData.
/// <para>
/// A generator rather than a checked-in constant for the same reason
/// <see cref="AliasProps"/> is one: a list maintained by hand goes stale the first time the input
/// moves, and silently.
/// </para>
/// </remarks>
public static class SchemaOrderTable
{
    // Bases the SDK's own framework supplies, which contribute no children of their own. Anything
    // else means the type inherits children this data does not describe — SdtElement is not in the
    // schema at all — and a container it cannot fully state is one it should say nothing about.
    static readonly HashSet<string> frameworkBases = new(StringComparer.Ordinal)
    {
        "OpenXmlCompositeElement",
        "OpenXmlPartRootElement",
        "OpenXmlLeafElement",
        "OpenXmlLeafTextElement"
    };

    public static string Generate()
    {
        var containers = Containers(out var skipped);
        var prefixes = Prefixes(containers);

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated>");
        builder.AppendLine("// Generated by OpenXmlKit.Tests.SchemaOrderTests. Do not edit by hand.");
        builder.AppendLine("//");
        builder.AppendLine("// Read from the OpenXML SDK's own schema data, vendored under");
        builder.AppendLine("// OpenXmlKit.Tests/SchemaData, which is where the SDK's code generator reads particle");
        builder.AppendLine("// order from: every type with children whose composite type is a sequence, and whose base");
        builder.AppendLine("// class is one the framework supplies rather than another element.");
        builder.AppendLine("//");
        builder.AppendLine($"// The {skipped} containers that inherit children from another element are left out. Their");
        builder.AppendLine("// bases are not all in the schema data - SdtElement is not there at all - so nothing could");
        builder.AppendLine("// state where an inherited child goes. A container with no entry is one Place appends to,");
        builder.AppendLine("// which is what happened before this existed.");
        builder.AppendLine("// </auto-generated>");
        builder.AppendLine();
        builder.AppendLine("namespace OpenXmlKit.Word;");
        builder.AppendLine();
        builder.AppendLine("public static partial class SchemaOrder");
        builder.AppendLine("{");
        builder.AppendLine("    // Element namespace to prefix, so a child read back off a document can be matched");
        builder.AppendLine("    // against the table below by the same key the schema writes.");
        builder.AppendLine("    static readonly Dictionary<string, string> prefixes = new(StringComparer.Ordinal)");
        builder.AppendLine("    {");
        foreach (var prefix in prefixes.OrderBy(_ => _.Key, StringComparer.Ordinal))
        {
            builder.AppendLine($"        [\"{prefix.Value}\"] = \"{prefix.Key}\",");
        }

        builder.AppendLine("    };");
        builder.AppendLine();
        builder.AppendLine("    // The children of each container, in the sequence the schema states, keyed by the name");
        builder.AppendLine($"    // the SDK gives the container's class. Space separated to keep this a table rather");
        builder.AppendLine($"    // than {containers.Count} array literals.");
        builder.AppendLine("    static readonly Dictionary<string, string> sequences = new(StringComparer.Ordinal)");
        builder.AppendLine("    {");
        foreach (var container in containers)
        {
            builder.AppendLine($"        [\"{container.Key}\"] =");
            builder.AppendLine($"            \"{string.Join(" ", container.Value)}\",");
        }

        builder.AppendLine("    };");
        builder.AppendLine("}");
        return builder.ToString();
    }

    static List<KeyValuePair<string, List<string>>> Containers(out int skipped)
    {
        using var document = JsonDocument.Parse(Read("wordprocessingml.json"));
        var result = new List<KeyValuePair<string, List<string>>>();
        skipped = 0;

        foreach (var type in document.RootElement.GetProperty("Types").EnumerateArray())
        {
            if (!type.TryGetProperty("Children", out var children) ||
                children.GetArrayLength() == 0 ||
                !type.TryGetProperty("ClassName", out var className))
            {
                continue;
            }

            // A choice permits its children in any order, so stating one would invent a constraint
            // the schema does not impose.
            var composite = type.TryGetProperty("CompositeType", out var value) ? value.GetString() : null;
            if (composite is not (null or "None" or "OneSequence"))
            {
                continue;
            }

            var baseClass = type.TryGetProperty("BaseClass", out var basedOn) ? basedOn.GetString() : null;
            if (baseClass != null &&
                !frameworkBases.Contains(baseClass))
            {
                skipped++;
                continue;
            }

            var names = children
                .EnumerateArray()
                .Select(_ => _.GetProperty("Name").GetString()!.Split('/')[^1])
                .ToList();
            result.Add(new(className.GetString()!, names));
        }

        result.Sort((left, right) => string.CompareOrdinal(left.Key, right.Key));
        return result;
    }

    static Dictionary<string, string> Prefixes(List<KeyValuePair<string, List<string>>> containers)
    {
        var used = containers
            .SelectMany(_ => _.Value)
            .Select(_ => _.Split(':')[0])
            .ToHashSet(StringComparer.Ordinal);

        using var document = JsonDocument.Parse(Read("namespaces.json"));
        var result = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (var entry in document.RootElement.EnumerateArray())
        {
            var prefix = entry.GetProperty("Prefix").GetString();
            if (prefix != null &&
                used.Contains(prefix))
            {
                result[prefix] = entry.GetProperty("Uri").GetString()!;
            }
        }

        var missing = used.Except(result.Keys).ToList();
        Assert.That(missing, Is.Empty, "every prefix the table uses needs a namespace");
        return result;
    }

    static string Read(string name)
    {
        var assembly = typeof(SchemaOrderTable).Assembly;
        var resource = assembly.GetManifestResourceNames().Single(_ => _.EndsWith(name, StringComparison.Ordinal));
        using var stream = assembly.GetManifestResourceStream(resource)!;
        using var reader = new StreamReader(stream);
        return reader.ReadToEnd();
    }
}
