import json, io

SCHEMA = r'C:/Code/Open-XML-SDK/data/schemas/schemas_openxmlformats_org_wordprocessingml_2006_main.json'
NAMESPACES = r'C:/Code/Open-XML-SDK/data/namespaces.json'
OUT = r'C:/Code/Papyrine/OpenXmlKit/src/OpenXmlKit/Word/SchemaOrder.Table.cs'

schema = json.load(io.open(SCHEMA, encoding='utf-8'))
namespaces = json.load(io.open(NAMESPACES, encoding='utf-8'))

# Only a sequence has an order to state. A choice permits its children in any order, so listing one
# would invent a constraint the schema does not impose.
rows = []
for t in schema['Types']:
    kids = t.get('Children')
    if not kids or t.get('CompositeType') not in ('OneSequence', None, 'None'):
        continue
    name = t.get('ClassName')
    if not name:
        continue
    order = [k['Name'].split('/')[-1] for k in kids]
    rows.append((name, order))

rows.sort(key=lambda r: r[0])

used = set()
for _, order in rows:
    for child in order:
        used.add(child.split(':')[0])

uris = {}
for entry in namespaces:
    prefix = entry.get('Prefix')
    if prefix in used:
        uris[prefix] = entry.get('Uri')

missing = used - set(uris)
assert not missing, missing

lines = []
lines.append('// <auto-generated>')
lines.append('// Generated from the OpenXML SDK\'s own schema data —')
lines.append('// data/schemas/schemas_openxmlformats_org_wordprocessingml_2006_main.json in')
lines.append('// dotnet/Open-XML-SDK — which is where the SDK\'s code generator reads the particle')
lines.append('// order from. Regenerating means re-running the generator against a newer checkout of')
lines.append('// that repository; SchemaOrderTests pins enough of the result to notice a bad one.')
lines.append('// </auto-generated>')
lines.append('')
lines.append('namespace OpenXmlKit.Word;')
lines.append('')
lines.append('public static partial class SchemaOrder')
lines.append('{')
lines.append('    // Element name to prefix, so a child read back off a document can be matched against')
lines.append('    // the table below by the same key the schema uses.')
lines.append('    static readonly Dictionary<string, string> prefixes = new(StringComparer.Ordinal)')
lines.append('    {')
for prefix in sorted(uris):
    lines.append('        ["%s"] = "%s",' % (uris[prefix], prefix))
lines.append('    };')
lines.append('')
lines.append('    // The children of each container, in the sequence the schema states, keyed by the name')
lines.append('    // the SDK gives the container\'s class. Space separated to keep this a table rather')
lines.append('    // than %d array literals.' % len(rows))
lines.append('    static readonly Dictionary<string, string> sequences = new(StringComparer.Ordinal)')
lines.append('    {')
for name, order in rows:
    lines.append('        ["%s"] =' % name)
    lines.append('            "%s",' % ' '.join(order))
lines.append('    };')
lines.append('}')

io.open(OUT, 'w', encoding='utf-8', newline='\r\n').write('\n'.join(lines) + '\n')
print('wrote', OUT)
print('containers:', len(rows), ' prefixes:', len(uris))
